apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deploy
on:
  push:
    branches:
      - "**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - uses: gmaxey/app-model/Deploy@main
        name: Deploy application
        kind: deploy
        with:
          connectionPort: "${{ vars.CONNECTION_PORT }}"