apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    environment: gpm-qa
    steps:
      - uses: gmaxey/app-model/Deploy@main
        name: Deploy application
        id: deploy
        kind: deploy
        with:
          connectionPort: "${{ vars.CONNECTION_PORT }}"
      - run: echo "${{ steps.deploy.outputs.connectionUrl }}"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh