apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deploy
on:
  push:
    branches:
      - "**"
jobs:
  deploy:
    steps:
      - uses: gmaxey/comp1/install@v1
        name: Install comp1
        kind: deploy
        with:
          version: "1"
      - uses: gmaxey/comp2/install@v1
        name: Install comp2
        kind: deploy
        with:
          version: "2"